theme: minima
name: The Artificers Guild
author:
  name: Samedi
excerpt_separator: <!--break-->

markdown: kramdown

sass:
    sass_dir: _sass

exclude:
    [ _source/, Gemfile, Gemfile.lock, CNAME ]

plugins:
    [ jekyll-paginate ]

paginate: 5
paginate_path: "/blog/page:num"
